version: "3.7"
services:
  web:
    container_name: web_server
    build: ./fedora_server/
    image: fedora_server:0.4
    working_dir: /var/www/html/
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  db: 
    container_name: db_server
    image: fedora_server:0.4
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  ansible:
    container_name: ansible_server
    build: ./fedora_client/
    image: fedora_client:0.4
    working_dir: /home/
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
